FROM openjdk
WORKDIR usr/src
ADD ./target/product-webapp-service-0.0.1-SNAPSHOT.jar /usr/src/product-webapp-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","product-webapp-service-0.0.1-SNAPSHOT.jar"]
