FROM openjdk
WORKDIR usr/src
ADD ./target/notification-service-0.0.1-SNAPSHOT.jar /usr/src/notification-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","notification-service-0.0.1-SNAPSHOT.jar"]
